### ISSUE TITLE
コメントの扱い

### ISSUE THREAD

**Issue by Alpha15** [YonezawaAkira/yonezawa#1]
不要になったコメントアウトを消す。  
コメントで何をしているか書く。

**Comment by YonezawaAkira** [comment]
お前もやっとるんか？

**Comment by Alpha15** [comment]
> お前もやっとるんか？

やってます。それが普通です。

**Comment by YonezawaAkira** [comment]
嘘つけ、昔のコード出すぞ

**Comment by Alpha15** [comment]
> 嘘つけ、昔のコード出すぞ

今の話をしてるんですが。

**Comment by YonezawaAkira** [comment]
これも昔のコードなので関係ないですよ

**Comment by Alpha15** [comment]
> これも昔のコードなので関係ないですよ

今も昔も関係ないです。

**Comment by YonezawaAkira** [comment]
じゃあ昔のあなたのコードも関係あるじゃないですか

**Comment by Alpha15** [comment]
> じゃあ昔のあなたのコードも関係あるじゃないですか

@ヒカキン  
助けて

**Comment by YonezawaAkira** [comment]
＾ー＾

**Comment by Alpha15** [comment]
> closed this as completed now  
  
じゃないが？

**Comment by YonezawaAkira** [comment]
**クローズしましたよ**

**Comment by Alpha15** [comment]
**クローズしてません**
